In [3]:
!pip install scipy

  Using cached scipy-1.17.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Using cached scipy-1.17.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.2 MB)

[notice] A new release of pip is available: 26.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip


In [11]:
import numpy as np

datos = np.array([1,12, 45, 7, 23, 67,67, 34, 89, 56, 11, 42])

## Medidas de tendencia central.

In [12]:
print(np.mean(datos))       
print(np.median(datos))     
# Moda no está en NumPy, se usa scipy:
from scipy import stats
print(stats.mode(datos))

37.833333333333336
38.0
ModeResult(mode=np.int64(67), count=np.int64(2))


## Medidas de dispersión.

In [13]:
print(np.std(datos))        # Desviación estándar
print(np.var(datos))        # Varianza
print(np.ptp(datos))        # Rango (max - min)

26.84471808175472
720.6388888888888
88


## Valores extremos y posición.

In [14]:
print(np.min(datos))        # Mínimo
print(np.max(datos))        # Máximo
print(np.argmin(datos))     # Índice del mínimo
print(np.argmax(datos))     # Índice del máximo
print(np.percentile(datos, [25, 50, 75]))  # Cuartiles

1
89
0
8
[11.75 38.   58.75]


## Operaciones sobre matrices.

In [16]:
matriz = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

print(np.mean(matriz))# Media
print(np.mean(matriz, axis=0))   # Media por columna
print(np.mean(matriz, axis=1))   # Media por fila
print(np.sum(matriz, axis=0))    # Suma por columna

50.0
[40. 50. 60.]
[20. 50. 80.]
[120 150 180]


## Correlación y Varianza

In [19]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])

print(np.corrcoef(x, y))    # Matriz de correlación de Pearson
print(np.cov(x, y))         # Matriz de covarianza

[[1.         0.77459667]
 [0.77459667 1.        ]]
[[2.5 1.5]
 [1.5 1.5]]
